### PR TITLE
Psychopy

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
Add psychopy section

### CODE REVIEW

**Comment by jona-sassenhagen** [comment]
@aylinsgl better ...

**Comment by aylinsgl** [comment]
If you want to check what the html looks like you can type "make html" in the docs directory in the terminal. The hmtl.index file will be under nbuild/html.

Am Mi., 9. Jan. 2019 um 16:43 Uhr schrieb jona-sassenhagen <
notifications@github.com>:

**Comment by jona-sassenhagen** [comment]
Thanks, I built it and it looks quite nice.

**Comment by jona-sassenhagen** [comment]
@aylinsgl do I need to push (& eventually merge) the build I did myself for it to show up on the website, or is it automatically build?

**Comment by aylinsgl** [comment]
Yes exactly, the readthedocs has a webhook to the repo, so as soon as you
push it will build in readthedocs

Am Do., 10. Jan. 2019, 13:33 hat jona-sassenhagen <notifications@github.com>
geschrieben:

**Comment by jona-sassenhagen** [comment]
Argh the commit history look sway too embarrassing :D I think I'll close and make a new pr.

**Pull request closed without merging**
