### PR TITLE
redo psychopy init

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
Computers: they are hard to use.

### CODE REVIEW

**Comment by DejanDraschkow** [comment]
very cool jona! ok, github might be a bit annoying for first drafts of chapters when there is a lot of editing and commenting to do..  maybe we do it like BIDS, where we work on gdocs on the first draft and push it when it is ready? 
maybe here: https://drive.google.com/drive/folders/1fCc1JDdZGUcT61lHl0hbxnA4-bxAnyDa?usp=sharing

**Comment by DejanDraschkow** [comment]
@jona-sassenhagen you want to throw it on gdrive now? we can also just merge it now and I can go through the little things on a seperate push..  your call

**Comment by jona-sassenhagen** [comment]
There is a lot of material missing first ...

But sure, I can throw the text so far on google docs for *comments*.

**Comment by jona-sassenhagen** [comment]
https://docs.google.com/document/d/182Jf28U1_KD2AnqYCgD1lAUSQEp6-dI9SXmyEPi8x7c/edit#bookmark=id.gjdgxs

here is the rst converted to docx with ```pandoc -o psychopy.docx Programming\ Experiments\ in\ Psychopy.rst```

**Comment by jona-sassenhagen** [comment]
@aylinsgl @DejanDraschkow feel free to comment here or there, remember deadline is on the 16th, so I would like to have things to show until then :)

**Comment by jona-sassenhagen** [comment]
I hate google docs

**Comment by jona-sassenhagen** [comment]
Would appreciate quick reviews & merge! @DejanDraschkow @aylinsgl

**Comment by jona-sassenhagen** [comment]
It renders nicely now IMO.

**Comment by DejanDraschkow** [comment]
wont be able to review the latest changes until tomorrow evening so I am fine with merging now!

**Comment by jona-sassenhagen** [comment]
hm ok ... @aylinsgl I'd still appreciate if you could take a look, the commits somehow include changes in files I don't remember touching?

**Comment by aylinsgl** [comment]
Can you tell me which files? I cant find anything

**Comment by DejanDraschkow** [comment]
tsup here? is it ready for merge? :)

**Comment by jona-sassenhagen** [comment]
Ok, hit it ... let's hope this works.

**Comment by DejanDraschkow** [comment]
@aylinsgl does the branch look good to you locally? if so then you can merge it!

**Comment by jona-sassenhagen** [comment]
https://smobsc.readthedocs.io/en/latest/chapter_exp/Programming%20Experiments%20in%20Psychopy.html

It's not there, correct? @aylinsgl

**Comment by aylinsgl** [comment]
Yes unfortunately :( I will check it out next week, probably missed
something

Am Sa., 26. Jan. 2019, 19:44 hat jona-sassenhagen <notifications@github.com>
geschrieben:

**Pull request merged**
